apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      imagePullSecrets:
        - name: {{ .Values.app.pullSecret }}
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          
          # Проверки здоровья (Probes)
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.app.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.app.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            
          env:
            - name: PORT
              value: "{{ .Values.app.port }}"
            - name: MONGO_URI
              value: "{{ .Values.mongodb.uri }}"