name: CI/CD Build and Deploy

on:
  push:
    branches:
      - main
      - feature/*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Генерируем теги.
      # type=sha создаст тег вида: sha-8a2b3c1 (короткий хэш коммита)
      # type=raw создаст тег: latest
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1. Копируем папку с чартом на сервер (чтобы обновились конфиги, если вы их меняли)
      # Мы НЕ копируем старую папку k8s/, только my-chart/
      - name: Copy Helm Chart to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 105
          source: "my-chart/*"
          target: "app-deploy" # На сервере появится ~/app-deploy/my-chart

      # 2. Заходим по SSH и обновляем релиз через Helm
      - name: Deploy via Helm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 105 
          # Передаем полный хэш коммита, чтобы внутри скрипта его обрезать
          envs: GITHUB_SHA
          script: |
            export KUBECONFIG=~/.kube/config
            
            # Формируем тот же тег, который создал Docker Metadata (sha + 7 символов коммита)
            # GitHub передает полный SHA, мы его обрезаем до 7 символов
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
            IMAGE_TAG="sha-$SHORT_SHA"
            
            echo "Deploying version: $IMAGE_TAG"

            # Helm Upgrade
            # --set app.image.tag=$IMAGE_TAG -> подменяет версию образа на лету
            # --atomic -> если приложение не запустится, Helm сам откатит изменения назад!
            helm upgrade --install arenda ~/app-deploy/my-chart \
              --set app.image.tag=$IMAGE_TAG \
              --atomic \
              --timeout 5m